version: '3.8'

networks:
  friends:
    external: false

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    restart: always
    environment:
      - ZOOKEEPER_CLIENT_PORT=2182
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - friends

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - friends
    depends_on:
      - zookeeper
    restart: always
    environment:
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2182
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://kafka:29092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT_INTERNAL

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_accounts_database
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql   # Mount SQL script
    ports:
      - "3307:3306"
    networks:
      - friends

  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mongodb
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro  # Mount MongoDB initialization script
    ports:
      - "27018:27017"
    networks:
      - friends

  grpc-sql-user-account-service:
    build:
      context: ./GrpcSqlUserService
      dockerfile: Dockerfile
    container_name: grpc_sql_user_account_service
    ports:
      - "8080:80"
    depends_on: 
        - kafka
    networks:
      - friends

  user-account-service-api:
    build:
      context: ./UserAccountService
      dockerfile: Dockerfile
    container_name: user_account_service_api
    ports:
      - "8000:80"
    networks:
      - friends

  grpc-mongo-profile-service:
    build:
      context: ./GrpcMongoProfileService
      dockerfile: Dockerfile
    container_name: grpc_mongo_profile_service
    ports:
      - "8004:80"
    networks:
      - friends

  grpc-mongo-friend-service:
    build:
      context: ./GrpcMongoFriendsService
      dockerfile: Dockerfile
    container_name: grpc_mongo_friend_service
    ports:
      - "8005:80"
    networks:
      - friends

  grpc-mongo-posting-service:
    build:
      context: ./GrpcMongoPostingService
      dockerfile: Dockerfile
    container_name: grpc_mongo_posting_service
    ports:
      - "8001:80"
    networks:
      - friends

  grpc-mongo-messaging-service:
    build:
      context: ./GrpcMongoMessagingService
      dockerfile: Dockerfile
    container_name: grpc_mongo_messaging_service
    ports:
      - "8008:80"
    networks:
      - friends

  profile-service-api:
    build:
      context: ./ProfileService
      dockerfile: Dockerfile
    container_name: profile_service_api
    ports:
      - "8002:80"
    networks:
      - friends

  posting-service-api:
    build:
      context: ./PostingService
      dockerfile: Dockerfile
    container_name: posting_service_api
    ports:
      - "8006:80"
    networks:
      - friends

  friend-service-api:
    build:
      context: ./UserFriendsService
      dockerfile: Dockerfile
    container_name: friend_service_api
    ports:
      - "8007:80"
    networks:
      - friends

  mongo-kafka-consumer-service:
    build:
      context: ./MongoKafkaConsumerService
      dockerfile: Dockerfile
    container_name: mongo_kafka_consumer_service
    depends_on:
      - kafka
    ports:
      - "8003:80"
    networks:
      - friends

  #blazor-app:
  #  build:
  #    context: ./FriendsBlazorApp
  #    dockerfile: Dockerfile
  #  container_name: friends_blazor_app
  #  ports: 
  #   - "8999:80"
  #  networks:
  #    - friends

volumes:
  mysql_data:
  mongo_data:
